name: Sanepar Monitor

on:
  schedule:
    - cron: "*/15 * * * *"
    - cron: "0 11 * * *"
    - cron: "0 14 * * *"
    - cron: "0 17 * * *"
    - cron: "0 23 * * *"

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run monitor
        run: python sanepar_monitor.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Commit status file
        run: |
          if [ -f ultimo_status.json ]; then
            git config --global user.name "github-actions"
            git config --global user.email "github-actions@github.com"
            
            git add ultimo_status.json
            
            # Se houver mudanças, faz o commit
            if ! git diff --cached --quiet; then
              git commit -m "Atualiza status monitor"
              
              # Garante que está sincronizado com a main antes de empurrar
              git pull --rebase origin main
              git push
            else
              echo "Nenhuma alteração detectada no status."
            fi
          else
            echo "Nenhum arquivo de status encontrado."
          fi
