name: Sanepar Monitor

on:
  schedule:
    - cron: "0 09 * * *"
    - cron: "0 15 * * *"
    - cron: "0 20 * * *"

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run monitor
        run: python sanepar_monitor.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Commit status files
        run: |

          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # adiciona arquivos mesmo se forem novos
          git add ultimo_status.json ultimo_alerta_diario.json 2>/dev/null || true

          # verifica alterações
          if git diff --cached --quiet; then
            echo "Nenhuma alteração para commit."
          else

            git commit -m "Atualiza status monitor"

            # atualiza branch antes do push
            git pull --rebase origin main

            git push
          fi
